[package]
name = "async"
version = "0.1.0"
authors = ["NerdyPepper <akshayoppiliappan@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.9", features = ["tokio-compat"] }
hyper = "0.12.9"
tokio = { version = "0.1.11", features = ["async-await-preview"] }
